### ISSUE TITLE
Should be able to construct `Request` with a `Request` as first constructor parameter

### ISSUE THREAD

**Issue by josephliccini** [pinterest/service-workers#104]
https://developer.mozilla.org/en-US/docs/Web/API/Request/Request#Parameters

> *input*
> Defines the resource that you wish to fetch. This can either be:
> - A USVString containing the direct URL of the resource you want to fetch.
> - **A Request object, effectively creating a copy. ...**

**Comment by jeffposnick** [comment]
(That's really funny—I was literally making changes to Workbox's fork of the `Request` mock to support that as I saw this issue come in: https://github.com/GoogleChrome/workbox/pull/1825/files#diff-e573d7bcd8df034de440d1e97ba36a5eR15)

**Comment by josephliccini** [comment]
😆 good timing!

**Comment by josephliccini** [comment]
btw, are you planning to upstream these into this repository or shall I open a CR?

**Comment by jeffposnick** [comment]
We aren't planning to upstream this change, but you can go ahead and do so using that code or something similar.

(The [Workbox mocks](https://github.com/GoogleChrome/workbox/tree/master/infra/testing/sw-env-mocks) have unfortunately diverged a decent amount from the ones in this repo, and honestly, I think we're going to try to go in the direction of running unit tests inside of a browser instead of with a mocked environment in `node` in the future.)

**Comment by kommander** [comment]
@jeffposnick I guess you're not abandoning node unit tests completely? On the `sw-env-mocks`: I see the mocks are currently in the root of the monorepo, which is not distributed as an npm package. I want to play with some worker tests and would like to use the mocks from workbox. Do you think it would be feasible to extract the mocks in an npm package for independent re-use?

**Comment by jeffposnick** [comment]
The direction we're looking to move in for Workbox is to run unit tests inside of at least one real browser (ideally multiple real browsers). That's a bit of a challenge given our current testing setup, so we're going to continue using a combination of these mocks + https://github.com/GoogleChrome/workbox/tree/master/infra/testing/sw-env-mocks until that happens.

I do feel guilty that we haven't upstreamed many of our changes, but it hasn't been a priority. If you're open to doing some legwork and upstreaming them into this repo, that would probably be more generally useful than us releasing them as a new package.

CC: @philipwalton

**Comment by zackargyle** [comment]
I would be super happy to review some upstream PRs 👍

**Comment by kommander** [comment]
Ok kool, I would be willing to put some sweat into this. My first approach would be:

- Extend the service-worker-mocks with the missing mocks added in workbox
  - IDB mocks
  - importScripts 
  - registration.sync (SyncManager)
  - SyncEvent
  - URLSearchParams
  - BroadcastChannel
  - navigator.userAgent
  - Event
  - FileReader
- Diff and apply the changes to the models from workbox:
  - Blob
  - ExtendableEvent
  - fetch (I'd prefer the workbox default response mock. Question: Should service-worker-mock also have a default fetch mock instead of manually applied as of now?)
  - FetchEvent
  - Headers
  - Request/Response
  - Use [workbox event-listeners](https://github.com/GoogleChrome/workbox/blob/master/infra/testing/sw-env.js#L25)

- Apply the [caches fix](https://github.com/GoogleChrome/workbox/blob/master/infra/testing/sw-env.js#L70-L78)
- Add pathname to sw location (I need that)
- Finally: Let [sw-env.js in workbox](https://github.com/GoogleChrome/workbox/blob/master/infra/testing/sw-env.js) use service-worker-mocks module only. It's only injected in the [mocha/nyc script in package.json](https://github.com/GoogleChrome/workbox/blob/master/package.json#L9)?

That should cover it basically. Let me know what you think and what I forgot.

**Comment by kommander** [comment]
@zackargyle here is a PR https://github.com/pinterest/service-workers/pull/109

**Comment by kommander** [comment]
@jeffposnick I just found that the non-existing DOMException will fail in node here https://github.com/GoogleChrome/workbox/compare/next#diff-20f922317958833448b3a5206f60f35eR31. I mocked that in my PR. 

What are your thoughts on the licensing? I saw the next branch is MIT now.

**Comment by jeffposnick** [comment]
Thanks a ton for doing this work, @kommander! 👍 

Yup, we've moved to MIT for Workbox v4. (Workbox v3 was Apache 2.0.) I am not an expert, but I do not anticipate any issues there.

**Comment by kommander** [comment]
My legs hurt. Was worth it. I'll remove the Apache license then and add attribution notices where applicable. Hope this can land on npm soonish.

**Comment by kommander** [comment]
@jeffposnick @zackargyle I went a bit overboard and am running full client/worker tests with a separate context now, because browser test setup really is tricky and cumbersome https://github.com/kommander/service-workers/compare/workbox-mock-upstream...kommander:sandboxed#diff-93bfb83635f471033b2b4a220968dc85 But it allows for tests like this:
```js
self.addEventListener('message', (event) => {
  if (event.data === 'hi') {
    event.ports[0].postMessage('Nice to meet you');
  }
});
```
```js
const { makeClientServiceWorkerEnv } = require('../index');
const path = require('path');

describe('Sandbox Messaging', () => {
  beforeEach(() => {
    Object.assign(global, makeClientServiceWorkerEnv());
    jest.resetModules();
  });

  it('can post a message', (done) => {
    navigator.serviceWorker.ready.then(registration => {
      const channel = new MessageChannel();
      channel.port1.onmessage = (event) => {
        expect(event.data).toEqual('Nice to meet you');
        done();
      };
      registration.active.postMessage('hi', [channel.port2]);
    });

    const swPath = path.resolve(__dirname, 'fixtures/sw.js');
    navigator.serviceWorker.register(swPath);
  });
});
```

**Comment by zackargyle** [comment]
Thanks for all your hard work on this @kommander! Closing out this issue.
