### ISSUE TITLE
https://in.pinterest.com doesn't load, sw.js failed error.

### ISSUE THREAD

**Issue by foo-baar** [pinterest/service-workers#54]
Hello,

I am using chrome canary (latest version) on Mac Sierra, loading https://in.pinterest.com always fails with browser displaying below error:

![screen shot 2017-10-12 at 9 14 42 am](https://user-images.githubusercontent.com/13655874/31478417-d3c9d544-af2d-11e7-8ad5-85bc1b016ecd.png)

In dev tools I see this issue:

![screen shot 2017-10-12 at 9 15 37 am](https://user-images.githubusercontent.com/13655874/31478435-f3f5bafe-af2d-11e7-88e3-5e3996799b5b.png)

Very frustrating, please guide me if I can do something to fix it myself.

Danke ✌️

**Comment by arthuralee** [comment]
Could you run `curl -I https://in.pinterest.com/sw.js` in your command line and let us know what the output is? Thanks!

**Comment by foo-baar** [comment]
@arthuralee : Here you go:
![screen shot 2017-10-13 at 12 16 20 am](https://user-images.githubusercontent.com/13655874/31513384-d2fb0fec-afab-11e7-823f-59be5ceec646.png)

**Comment by arthuralee** [comment]
Unfortunately it may be an issue with your computer or network (see similar error at https://forums.developer.apple.com/thread/19321). Basically, your computer has determined our TLS handshake is unacceptable, though our servers are operating correctly as far as we know (https://www.ssllabs.com/ssltest/analyze.html?d=in.pinterest.com&hideResults=on). It may be due to incorrectly set network or time.

**Comment by foo-baar** [comment]
And you don't think there is any way to fix it ? BTW I am using macbook air, sierra OS

**Comment by zackargyle** [comment]
Unfortunately it seems like an issue on your end. If you're able to diagnose and it turns out to be from our codebase, let us know and we'll happily fix.
