### ISSUE TITLE
[service-worker-mock] Add a reset function

### ISSUE THREAD

**Issue by gauntface** [pinterest/service-workers#62]
In the indexedDB mock we're using, it comes with a useful reset function that basically clears out the databases and it would be handy to have the same thing in the service-worker-mock.

Main use case I just hit is having the ability to clear out any event listeners so test would trigger previous events.

What do people think? Happy to put together a PR.

**Comment by zackargyle** [comment]
Currently you can just call `makeServiceWorkerEnv()` for each test and that should work. It's not too heavy of a call, but I agree it'd be nice to have a lighter-weight `reset` mechanism. Maybe each class could define a `reset` much like `snapshot` that trickles down through it's children.

```
// for everything
self.resetSwEnv();
// just for caches
self.caches.reset();
// just for listeners
self.listeners.reset();
```

As an aside, might be worth renaming `listeners` since it's pretty generic and in global scope.

**Comment by zackargyle** [comment]
Added in `1.7.0`
